name: Test

on: push
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Test TouchUp compilation without creating any usable releases
    strategy:
      matrix:
        os: [ ubuntu-latest ] #todo
        enable-yt: [ true, false ]
        enable-upd: [ true, false ]
        include:
          - enable-yt: true
            yt: "-F youtube"
          - enable-upd: true
            upd: "-F update"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Set FFmpeg git version
        run: |
          FFMPEG_VER=$(cat ./touchup/ffmpeg_ver.txt)
          echo "FFMPEG_VER=$FFMPEG_VER" >> $GITHUB_ENV
      - name: Install packages for FFmpeg
        run: apt install -y clang libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev pkg-config
      - name: Build TouchUp
        run: |
          cargo build --no-default-features ${{ matrix.enable-yt }} ${{ matrix.enable-upd }}
